//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4971
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FTP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AnonymousUser {
            get {
                object obj = ResourceManager.GetObject("AnonymousUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table cellpadding=&quot;0&quot; border=&quot;0&quot; style=&quot;color:#333333;font-family:Verdana;font-size:0.8em;height:91px;width:354px;&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;td align=&quot;center&quot; colspan=&quot;2&quot; style=&quot;color:White;background-color:#999966;font-size:0.9em;font-weight:bold;&quot;&gt;
        ///		Choose Folder&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;td width=&quot;93&quot;&gt;Selected Path&lt;/td&gt;
        ///		&lt;td width=&quot;255&quot;&gt;
        ///		&lt;input id=&quot;curSelectedPath&quot; readonly style=&quot;width:254;height:22&quot; value=&quot;--SelPath--&quot;&gt;&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;td colspan=&quot;2&quot;&gt;
        ///		&lt;select id=&quot;drvList&quot; style=&quot;height:180; width:3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DeleteUser {
            get {
                object obj = ResourceManager.GetObject("DeleteUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///	&lt;table id=&quot;tblBrowser&quot; cellspacing=&quot;0&quot; cellpadding=&quot;4&quot; border=&quot;0&quot; style=&quot;border:1px Solid #B5C7DE; background-color:#EEEECC;border-collapse:collapse; position: absolute; left:491px; top:87px; width:355px; height:226px;display:none;&quot;&gt;
        ///		&lt;tr&gt;
        ///			&lt;td id=&quot;tdDirectory&quot;&gt;
        ///			
        ///			&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///	&lt;/table&gt;
        ///	&lt;table cellspacing=&quot;0&quot; cellpadding=&quot;4&quot; border=&quot;0&quot; style=&quot;border:1px Solid #B5C7DE; background-color:#EEEECC;border-collapse:collapse; position: absolute; left:205px; top:87px; width:194px&quot; width=&quot;268 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap EditUser {
            get {
                object obj = ResourceManager.GetObject("EditUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;width:800px;height:455px;overflow:auto;&quot;&gt;&lt;p&gt;&lt;font size=&quot;5&quot;&gt;User Guide&lt;/font&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;font size=&quot;4&quot;&gt;Online Users&lt;/font&gt;&lt;/p&gt;
        ///&lt;ul&gt;
        ///	&lt;li&gt;Displays the list of all the users currently online in tabular format.&lt;/li&gt;
        ///	&lt;li&gt;This tabular record contains the following details&lt;br&gt;
        ///&amp;nbsp;&amp;nbsp;&amp;nbsp; &lt;b&gt;EndPoint&lt;/b&gt; : The IP Address and the Port no to which they 
        ///	were connected&lt;br&gt;
        ///&amp;nbsp;&amp;nbsp;&amp;nbsp; &lt;b&gt;User Name&lt;/b&gt; : The name used to login.&lt;br&gt;
        ///&amp;nbsp;&amp;nbsp;&amp;nbsp; &lt;b&gt;Current Directory&lt;/b&gt; - The dire [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;table cellspacing=&quot;0&quot; cellpadding=&quot;4&quot; border=&quot;0&quot; style=&quot;border:1px Solid #B5C7DE; background-color:#EEEECC;border-collapse:collapse; position: absolute; left:-1px; top:226px; width:197px&quot; width=&quot;268&quot;&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;
        ///&lt;table cellpadding=&quot;0&quot; border=&quot;0&quot; style=&quot;color:#333333;font-family:Verdana;font-size:0.8em;height:91px;width:187px&quot;&gt;
        ///&lt;tr&gt;
        ///&lt;td align=&quot;center&quot; colspan=&quot;2&quot; style=&quot;color:White;background-color:#999966;font-size:0.9em;font-weight:bold;&quot;&gt;
        ///Log In&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td align=&quot;right&quot; width=&quot;69&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;title&gt;Advanced FTP Server :: Control Panel :: Login&lt;/title&gt;
        ///&lt;script&gt;
        ///var FTPPort = &lt;%FTPPort%&gt;;
        ///var objRequest;
        ///var updations;
        ///var busyMessage;
        ///
        ///function RequestAsync(url, Params, UpdationBlock, ProcessingMessage)
        ///{
        ///	updations = UpdationBlock;
        ///	busyMessage = ProcessingMessage;
        ///	objRequest=null;
        ///	if (window.XMLHttpRequest)
        ///	{
        ///		// code for Firefox, Opera, IE7, etc.
        ///		objRequest=new XMLHttpRequest();
        ///  	}
        ///	else if (window.ActiveXObject)
        ///	{
        ///		// code for IE6, IE5
        ///		objReq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style&gt;
        ///input{color:#284E98;background-color:White;border-color:#507CD1;border-width:1px;border-style:Solid;font-family:Verdana;font-size:0.8em;}
        ///&lt;/style&gt;&lt;div&gt;
        ///	&lt;table cellspacing=&quot;0&quot; cellpadding=&quot;4&quot; border=&quot;0&quot; style=&quot;border:1px Solid #B5C7DE; background-color:#EEEECC;border-collapse:collapse; position: absolute; left:218px; top:103px; width:272px; height:101px&quot; width=&quot;268&quot;&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;
        ///			&lt;table cellpadding=&quot;0&quot; border=&quot;0&quot; style=&quot;color:#333333;font-family:Verdana;font-size:0.8em;height:91px;width:2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManageServices {
            get {
                return ResourceManager.GetString("ManageServices", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NewUser {
            get {
                object obj = ResourceManager.GetObject("NewUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///	&lt;table cellspacing=&quot;0&quot; cellpadding=&quot;4&quot; border=&quot;0&quot; style=&quot;border:1px Solid #B5C7DE; background-color:#EEEECC;border-collapse:collapse;width:100%;&quot;&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;
        ///			&lt;table cellpadding=&quot;0&quot; border=&quot;0&quot; style=&quot;color:#333333;font-family:Verdana;font-size:0.8em;width:100%;&quot;&gt;
        ///				&lt;tr&gt;
        ///					&lt;td align=&quot;center&quot; colspan=&quot;6&quot; style=&quot;color:White;background-color:#999966;font-size:0.9em;font-weight:bold;&quot;&gt;
        ///					Online Users&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr style=&quot;color:#FFFFFF;background-color:#999966;font-weight:bo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OnlineUsers {
            get {
                return ResourceManager.GetString("OnlineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;
        ///if(navigator.cookieEnabled == 0) document.write(&quot;&lt;p align=center&gt;&lt;b&gt;&lt;font color=\&quot;#FF0000\&quot; size=\&quot;4\&quot;&gt;Cookies are not enabled in your browser. To view this page you need to enable cookies.&lt;/font&gt;&lt;/b&gt;&lt;/p&gt;&quot;);
        ///else
        ///{
        ///document.cookie = &quot;SessionId=&quot;+Value+&quot;; path=/&quot;;
        ///document.location.href = &quot;Admin&quot;;
        ///}
        ///&lt;/script&gt;.
        /// </summary>
        internal static string PreRender {
            get {
                return ResourceManager.GetString("PreRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Configuration&gt;
        ///  &lt;SETTINGS&gt;
        ///    &lt;KEY NAME=&quot;MIN_PASSV_PORT&quot; VALUE=&quot;7000&quot; /&gt;
        ///    &lt;KEY NAME=&quot;MAX_PASSV_PORT&quot; VALUE=&quot;7100&quot; /&gt;
        ///    &lt;KEY NAME=&quot;FTP_PORT&quot; VALUE=&quot;21&quot; /&gt;
        ///    &lt;KEY NAME=&quot;AUTO_START_FTP&quot; VALUE=&quot;1&quot; /&gt;
        ///    &lt;KEY NAME=&quot;ENABLE_FTP_LOGGING&quot; VALUE=&quot;0&quot; /&gt;
        ///    &lt;KEY NAME=&quot;HTTP_PORT&quot; VALUE=&quot;9090&quot; /&gt;
        ///    &lt;KEY NAME=&quot;AUTO_START_HTTP&quot; VALUE=&quot;1&quot; /&gt;
        ///    &lt;KEY NAME=&quot;HTTP_LOGIN_ID&quot; VALUE=&quot;ADMIN&quot; /&gt;
        ///    &lt;KEY NAME=&quot;HTTP_PASSWORD&quot; VALUE=&quot;admin&quot; /&gt;
        ///    &lt;KEY NAME=&quot;ENABLE_NOT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///	&lt;table cellspacing=&quot;0&quot; cellpadding=&quot;4&quot; border=&quot;0&quot; style=&quot;border:1px Solid #B5C7DE; background-color:#EEEECC;border-collapse:collapse;width:100%;&quot;&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;
        ///			&lt;table cellpadding=&quot;0&quot; border=&quot;0&quot; style=&quot;color:#333333;font-family:Verdana;font-size:0.8em;width:100%;&quot;&gt;
        ///				&lt;tr&gt;
        ///					&lt;td align=&quot;center&quot; colspan=&quot;6&quot; style=&quot;color:White;background-color:#999966;font-size:0.9em;font-weight:bold;&quot;&gt;
        ///					User Account&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr style=&quot;color:#FFFFFF;background-color:#999966;font-weight:bo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserAccount {
            get {
                return ResourceManager.GetString("UserAccount", resourceCulture);
            }
        }
    }
}
